name: Build LaTeX PDF
on: [push]
jobs:
  build_latex:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v2
      - name: Compile LaTeX document
        uses: xu-cheng/latex-action@v2
        with:
          root_file: mainDoc.tex
          args: -bibtex -pdf -file-line-error -halt-on-error -interaction=nonstopmode
      - uses: actions/upload-artifact@v2
        with:
          name: ms-thesis-artifact
          path: mainDoc.pdf
